### ISSUE TITLE
Heroicons bug

### ISSUE THREAD

**Issue by hamrak** [LaravelDaily/FilaStart#11]
If you search for icons and that icon doesn't exists, it shows you a JSON:

<img width="492" alt="Snímka obrazovky 2024-07-06 o 8 07 53" src="https://github.com/LaravelDaily/FilaStart/assets/5807028/6a918958-fd30-4b1a-b50f-6dafe01c025d">

<img width="1324" alt="Snímka obrazovky 2024-07-06 o 8 29 35" src="https://github.com/LaravelDaily/FilaStart/assets/5807028/c11e02cd-1612-477f-bf94-4da88b9b5327">

**Comment by ModestasV** [comment]
Fixed by #12
