### ISSUE TITLE
unable to edit field

### ISSUE THREAD

**Issue by adesmuoih** [LaravelDaily/FilaStart#7]
Hello,

if I edit a field and try to save the changes, I always get the error: "The label has already been taken."
I think that somewhere it tries to insert the record instead of updating it. Unfortunately I wasn't able to locate 
the code. Probably somewhere in FieldsRelationManager?
Using php8.3 with sqlite.

brA

**Comment by ModestasV** [comment]
Hi, thanks for reporting this. Let me look at our validation rule. I might have set it incorrectly!

**Comment by ModestasV** [comment]
@adesmuoih Fixed with #8 -  new release coming up!

**Comment by adesmuoih** [comment]
thx a lot!
