### ISSUE TITLE
Parent dropdown is not populated

### ISSUE THREAD

**Issue by liljefelt** [LaravelDaily/FilaStart#9]
Hi and thank you for this great tool!

While playing around last night I noticed that the Parent dropdown is never populated in the /cruds/create and /cruds/{id}/edit forms.
Is there a trick to it, or is it just my setup?

My localhost is on Win 10 with PHP 8.3.3 + SQLite.
During install I run the "composer install" command with "--ignore-platform-reqs" to get around the pcntl requirement.

Everything else seems to be working fine.

**Comment by ModestasV** [comment]
Hi, it might be that you need to enter text to search for a CRUD - it depends how many you have!

But I will take a look at this later ;)

**Comment by liljefelt** [comment]
Hi Modestas, thanks for the quick response!

I'm not seeing anywhere to enter a search term when opening the dropdown, and the console is not showing any error messages except a bunch of "A form field element should have an id or name attribute".

![cruds](https://github.com/LaravelDaily/FilaStart/assets/8920695/82ccdf6c-a13b-4b92-86af-6cffac35fd21)
![edit-crud](https://github.com/LaravelDaily/FilaStart/assets/8920695/d80d0b45-e456-4c14-b7fc-0248164c52df)

**Comment by ModestasV** [comment]
Ohh, it makes sense now!

You need to create a CRUD with the type parent in order to populate it. This is not a nested resource thing, just a navigation group

**Comment by liljefelt** [comment]
Oh dear silly me, please close this whole topic.

I just noticed that cruds can be of type "Parent" 😅.

It works as expected now.

**Comment by ModestasV** [comment]
Happens to all of us!
